package com.chenfeng.hy.domain.model;

import java.util.Date;

public class CasesDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.cases_id
     *
     * @mbggenerated
     */
    private Long casesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cases_detail.update
     *
     * @mbggenerated
     */
    private Date update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.id
     *
     * @return the value of t_cases_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.id
     *
     * @param id the value for t_cases_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.cases_id
     *
     * @return the value of t_cases_detail.cases_id
     *
     * @mbggenerated
     */
    public Long getCasesId() {
        return casesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.cases_id
     *
     * @param casesId the value for t_cases_detail.cases_id
     *
     * @mbggenerated
     */
    public void setCasesId(Long casesId) {
        this.casesId = casesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.image
     *
     * @return the value of t_cases_detail.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.image
     *
     * @param image the value for t_cases_detail.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.content
     *
     * @return the value of t_cases_detail.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.content
     *
     * @param content the value for t_cases_detail.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.create_time
     *
     * @return the value of t_cases_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.create_time
     *
     * @param createTime the value for t_cases_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cases_detail.update
     *
     * @return the value of t_cases_detail.update
     *
     * @mbggenerated
     */
    public Date getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cases_detail.update
     *
     * @param update the value for t_cases_detail.update
     *
     * @mbggenerated
     */
    public void setUpdate(Date update) {
        this.update = update;
    }
}