package com.chenfeng.hy.domain.model;

import java.util.Date;

public class Position {
   
    private Long id;

    /**
     * 职位名称
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.address
     *
     * @mbggenerated
     */
    private String address;

    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.recruitment
     *
     * @mbggenerated
     */
    private String recruitment;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.id
     *
     * @return the value of t_position.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.id
     *
     * @param id the value for t_position.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.name
     *
     * @return the value of t_position.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.name
     *
     * @param name the value for t_position.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.address
     *
     * @return the value of t_position.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.address
     *
     * @param address the value for t_position.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.duty
     *
     * @param duty the value for t_position.duty
     *
     * @mbggenerated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.recruitment
     *
     * @return the value of t_position.recruitment
     *
     * @mbggenerated
     */
    public String getRecruitment() {
        return recruitment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.recruitment
     *
     * @param recruitment the value for t_position.recruitment
     *
     * @mbggenerated
     */
    public void setRecruitment(String recruitment) {
        this.recruitment = recruitment == null ? null : recruitment.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.create_time
     *
     * @return the value of t_position.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.create_time
     *
     * @param createTime the value for t_position.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.update_time
     *
     * @return the value of t_position.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.update_time
     *
     * @param updateTime the value for t_position.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}